import { createFileRoute } from "@tanstack/react-router";
import {
  navigationStructure,
  getTrail,
  getTrailActivities,
} from "@/lib/navigation/structure";
import { TrailGraph } from "@/components/navigation-viewer/TrailGraph";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Navigation structure viewer" },
      {
        name: "description",
        content:
          "Visualize study areas, trails, and activity nodes generated by the model.",
      },
    ],
  }),
  component: Index,
});

function Index() {
  const { studyAreas, activities } = navigationStructure;
  const totalActivities = activities.length;

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="mx-auto max-w-6xl px-6 py-6">
          <h1 className="text-2xl font-semibold tracking-tight">
            Navigation structure
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {studyAreas.length} study areas · {studyAreas.length} trails ·{" "}
            {totalActivities} activities
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-6xl space-y-10 px-6 py-8">
        {studyAreas.map((area) => {
          const trail = getTrail(area.trailId);
          if (!trail) return null;
          const trailActivities = getTrailActivities(trail.id);
          return (
            <section key={area.id} className="space-y-3">
              <div className="flex items-baseline gap-3">
                <h2 className="text-lg font-semibold">
                  Study area{" "}
                  <span className="font-mono text-base text-muted-foreground">
                    {area.id}
                  </span>
                </h2>
                <span className="text-xs text-muted-foreground">
                  order #{area.order} · trail{" "}
                  <span className="font-mono">{trail.id}</span> ·{" "}
                  {trailActivities.length} activities
                </span>
              </div>
              <TrailGraph trail={trail} activities={trailActivities} />
            </section>
          );
        })}

        <Legend />
      </main>
    </div>
  );
}

function Legend() {
  const items: { label: string; className: string }[] = [
    { label: "Locked", className: "bg-muted/40 border-border" },
    { label: "Available", className: "bg-primary/5 border-primary/60" },
    { label: "Unlocked", className: "bg-primary/10 border-primary" },
    { label: "In progress", className: "bg-primary/15 border-primary" },
    { label: "Completed", className: "bg-emerald-500/10 border-emerald-500/60" },
  ];
  return (
    <section className="rounded-lg border bg-card p-4">
      <h3 className="text-sm font-medium">Legend</h3>
      <div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">
        {items.map((i) => (
          <div key={i.label} className="flex items-center gap-2">
            <span
              className={`inline-block h-4 w-4 rounded border ${i.className}`}
            />
            {i.label}
          </div>
        ))}
      </div>
    </section>
  );
}
